sudo: false

language: python

python:
   - 2.7
   - 3.5

addons:
  apt:
    packages:
      - gnuplot

cache: pip

notifications:
  email: false

install:
   - pip install ipykernel metakernel
   - pip install --upgrade pytest>=3.0.6
   - pip install pytest-cov
   - pip install coveralls
   - python setup.py install
   - pip list

script:
   - make test

after_success:
   - coveralls --rcfile=.coveragerc
